"""changed user table to user_account

Revision ID: 0507c4fb336f
Revises: 6a740cb68857
Create Date: 2026-09-03 21:52:40.597816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0507c4fb336f'
down_revision: Union[str, Sequence[str], None] = '6a740cb68857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'user_account')
    op.drop_constraint('submission_user_id_fkey', 'submission', type_='foreignkey')
    op.alter_column('submission', 'user_id', new_column_name='user_account_id')
    op.create_foreign_key(op.f('submission_user_account_id_fkey'), 'submission', 'user_account', ['user_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('submission_user_account_id_fkey'), 'submission', type_='foreignkey')
    op.alter_column('submission', 'user_account_id', new_column_name='user_id')
    op.create_foreign_key('submission_user_id_fkey', 'submission', 'user', ['user_id'], ['id'])
    op.rename_table('user_account', 'user')
    # ### end Alembic commands ###
