"""adjusted submission memory row

Revision ID: 43eba0970a1d
Revises: 9bccff6592c6
Create Date: 2026-08-26 13:01:51.933673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43eba0970a1d'
down_revision: Union[str, Sequence[str], None] = '9bccff6592c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'memory',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'memory',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
