"""Added total test count column in submissions

Revision ID: 6a740cb68857
Revises: cf3573038439
Create Date: 2026-08-27 10:33:27.203097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a740cb68857'
down_revision: Union[str, Sequence[str], None] = 'cf3573038439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('total_test_number', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'total_test_number')
    # ### end Alembic commands ###
