"""adjusted submission BaseModel

Revision ID: 9bccff6592c6
Revises: 1b6b20e5ff30
Create Date: 2026-08-26 12:59:37.239326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bccff6592c6'
down_revision: Union[str, Sequence[str], None] = '1b6b20e5ff30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'date')
    # ### end Alembic commands ###
