"""Submission-table changed PK name: solution-id to id

Revision ID: 9f37a583add4
Revises: c5c2489b49a5
Create Date: 2026-08-18 17:35:31.685121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f37a583add4'
down_revision: Union[str, Sequence[str], None] = 'c5c2489b49a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('submission', 'solution_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('solution_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('submission', 'id')
    # ### end Alembic commands ###
