"""Initial schema setup

Revision ID: c5c2489b49a5
Revises:
Create Date: 2026-08-15 13:56:04.520302

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c5c2489b49a5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problem",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("desc", sa.String(length=2000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submission",
        sa.Column("solution_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("problem_id", sa.UUID(), nullable=False),
        sa.Column("source_code", sa.String(length=2000), nullable=False),
        sa.Column("memory", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.Column("time", sa.Numeric(precision=3, scale=5)),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("stderr", sa.String(length=300), nullable=True),
        sa.Column("stdin", sa.String(length=100), nullable=True),
        sa.Column("stdout", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("solution_id"),
    )
    op.create_table(
        "test_case",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stdin", sa.String(length=100), nullable=False),
        sa.Column("expected_output", sa.String(length=100), nullable=False),
        sa.Column("problem_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_case")
    op.drop_table("submission")
    op.drop_table("user")
    op.drop_table("problem")
    # ### end Alembic commands ###
