"""Refactored submission fields to better suit marking it as failed

Revision ID: c76de5b4bab5
Revises: f1ebe41a6161
Create Date: 2026-08-27 09:25:33.270899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76de5b4bab5'
down_revision: Union[str, Sequence[str], None] = 'f1ebe41a6161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('failed_test_case_id', sa.String(length=100), nullable=True))
    op.drop_column('submission', 'failed_stdin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('failed_stdin', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('submission', 'failed_test_case_id')
    # ### end Alembic commands ###
