"""Change failed_test_case_id to FK in submission table

Revision ID: cf3573038439
Revises: c76de5b4bab5
Create Date: 2026-08-27 09:45:53.924927

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cf3573038439"
down_revision: Union[str, Sequence[str], None] = "c76de5b4bab5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "submission",
        "failed_test_case_id",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.UUID(),
        postgresql_using='"failed_test_case_id"::uuid',
        existing_nullable=True,
    )
    op.create_foreign_key(
        None, "submission", "test_case", ["failed_test_case_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "submission", type_="foreignkey")
    op.alter_column(
        "submission",
        "failed_test_case_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=100),
        postgresql_using='"failed_test_case_id"::varchar',
        existing_nullable=True,
    )
    # ### end Alembic commands ###
