"""Update submission table

Revision ID: dfe4cc0abf92
Revises: 9f37a583add4
Create Date: 2026-08-18 19:09:38.512015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfe4cc0abf92'
down_revision: Union[str, Sequence[str], None] = '9f37a583add4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('submission', sa.Column('test_passed_number', sa.SmallInteger(), nullable=True))
    op.add_column('submission', sa.Column('failed_stdin', sa.String(length=100), nullable=True))
    op.add_column('submission', sa.Column('failed_stdout', sa.String(length=100), nullable=True))
    op.alter_column('submission', 'memory',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               nullable=True)
    op.alter_column('submission', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('submission', 'stdin')
    op.drop_column('submission', 'correct')
    op.drop_column('submission', 'stdout')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('stdout', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('submission', sa.Column('correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('submission', sa.Column('stdin', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('submission', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('submission', 'memory',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               nullable=False)
    op.drop_column('submission', 'failed_stdout')
    op.drop_column('submission', 'failed_stdin')
    op.drop_column('submission', 'test_passed_number')
    op.drop_column('submission', 'status')
    # ### end Alembic commands ###
