"""adjusted submission time row yet again

Revision ID: f1ebe41a6161
Revises: 86f71be049e2
Create Date: 2026-08-26 13:05:55.941831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ebe41a6161'
down_revision: Union[str, Sequence[str], None] = '86f71be049e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'time',
               existing_type=sa.NUMERIC(precision=3, scale=5),
               type_=sa.Numeric(precision=7, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'time',
               existing_type=sa.Numeric(precision=7, scale=3),
               type_=sa.NUMERIC(precision=3, scale=5),
               existing_nullable=True)
    # ### end Alembic commands ###
